---
- name: Check password for {{ openshift_htpasswd_user.name }}
  command: >-
    htpasswd -bv {{ htpasswd_file | quote }}
    {{ openshift_htpasswd_user.name | quote }}
    {{ openshift_htpasswd_user.password | quote }}
  register: r_check_htpasswd
  changed_when: false
  check_mode: false
  failed_when: false

- name: Set password for {{ openshift_htpasswd_user.name }}
  command: >-
    htpasswd -b {{ htpasswd_file | quote }}
    {{ openshift_htpasswd_user.name | quote }}
    {{ openshift_htpasswd_user.password | quote }}
  when: r_check_htpasswd.rc != 0
  check_mode: false
