---
- name: Delete htpasswd entries
  command: >-
    htpasswd -D {{ htpasswd_file | quote }} {{ username | quote }}
  loop: "{{ htpasswd_lines }}"
  loop_control:
    label: username
    loop_var: htpasswd_line
  vars:
    username: "{{ htpasswd_line.split(':')[0] }}"
    configured_users: >-
      {{ openshift_htpasswd_users | json_query('[].name') }}
  when: username not in configured_users
  check_mode: false
